name: bfit_tracker
description: A web and mobile application for fitness enthusiasts or just for people wanting to be healthy and fit, track your healthy lifestyle by touch of your finger.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: "2.0.1"

dependency_overrides:
  archive: ^3.0.0
  crypto: ^3.0.0
  xml: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  barcode_scan: ^3.0.1
  cached_network_image: ^2.3.3
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.4
  device_info: ^2.0.0
  dots_indicator: ^1.2.0
  equatable: ^2.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  fl_chart: ^0.20.1
  flare_flutter: ^2.0.6
  flutter_bloc: ^4.0.0
  flutter_dotenv: ^2.1.0
  font_awesome_flutter: ^8.10.0
  geolocator: ^7.0.1
  get: ^4.0.0-nullsafety.2
  googleapis: ^2.0.0
  google_sign_in: ^4.5.3
  health: 1.0.6
  height_slider: ^1.4.0-nullsafety
  http: ^0.13.0
  intl: ^0.17.0
  jiffy: ^4.0.0
  kt_dart: ^0.8.0
  meta: ^1.1.8
  nutrition: ^1.0.0
  openfoodfacts: ^1.0.1-beta
  percent_indicator: ^2.1.7+4
  recase: ^3.0.0
  transformer_page_view: ^0.1.6
  url_launcher: ^6.0.2
  weight_slider: ^1.2.0
  wiredash: ^0.6.2

dev_dependencies:
  dependency_validator: ^1.5.0
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: SF UI Text
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 700
