name: bfit_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: "1.12.13+hotfix.8"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.0.2
  bloc: ^3.0.0
  cloud_firestore: ^0.12.9+5
  curved_navigation_bar: ^0.1.2
  dots_indicator: ^1.0.0
  equatable: ^1.1.0
  firebase_auth: ^0.11.1
  flare_flutter: ^1.5.6
  flutter_bloc: ^3.2.0
  flutter_svg: ^0.15.0
  font_awesome_flutter: ^8.5.0
  geolocator: '^5.0.0'
  google_sign_in: ^4.0.1+3
  height_slider: ^1.1.3
  http: ^0.12.0+2
  meta: ^1.1.6
  percent_indicator: ^2.1.1
  transformer_page_view: ^0.1.6
  url_launcher: ^5.1.1
  weight_slider: ^1.0.2

dev_dependencies:
  dependency_validator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: SF UI Text
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
