name: bfit_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: "1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  bloc: ^4.0.0
  cloud_firestore: ^0.13.5
  curved_navigation_bar: ^0.3.2
  device_info: ^0.4.2+3
  dots_indicator: ^1.1.0
  equatable: ^1.1.1
  firebase_auth: ^0.16.0
  fl_chart: ^0.9.4
  flare_flutter: ^2.0.3
  flutter_bloc: ^4.0.0
  flutter_dotenv: ^2.1.0
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.8.1
  geolocator: ^5.3.1
  google_sign_in: ^4.4.4
  health: ^1.0.2
  height_slider: ^1.2.0
  http: ^0.12.1
  jiffy: ^3.0.1
  meta: ^1.1.8
  percent_indicator: ^2.1.3
  transformer_page_view: ^0.1.6
  url_launcher: ^5.4.5
  weight_slider: ^1.1.0

dev_dependencies:
  dependency_validator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: SF UI Text
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
