name: bfit_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: "1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.2.4
  flutter_bloc: ^0.13.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1
  meta: ^1.1.6
  curved_navigation_bar: ^0.1.2
  flutter_svg: ^0.15.0
  auto_size_text: ^2.0.2
  geolocator: '^5.0.0'
  http: ^0.12.0+2
  url_launcher: ^5.1.1
  percent_indicator: ^2.1.1
  font_awesome_flutter: ^8.5.0
  flare_flutter: ^1.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/

  fonts:
    - family: SF UI Text
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
